name: Ballerina PR validation
on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up go
      uses: actions/setup-go@v1
      with:
        go-version: '1.10.4'
    - name: Set up ruby
      uses: clupprich/ruby-build-action@master
      id: ruby
      with:
        ruby-version: 2.5

    - name: Clone the ballerina-release repo
      run: git clone https://github.com/ballerina-platform/ballerina-release.git
    - name: Go to the ballerina example tool folder 
      run: cd ballerinaByExample
    - name: Execute the bash file
      run: tools/build-bbe.sh bbe_gen_tool v1-0

    - name: Clone the ballerina-dev-website repo
      env: 
        GITHUB_TOKEN : ${{secrets.SECRET_BAL}}
      run: git clone https://github.com/ballerina-platform/ballerina-dev-website.git
      
    - name: Go to the cloned folder
      run: cd ballerina-dev-website
    - name: Build the site
      run: sudo jekyll build
    - name: Send PR to ballerina-dev-website
      run: |
        git checkout -b newBranch
        
        git config user.email "sumangala028@gmail.com"
        git config user.name "sumangala028"
        
        git add --all
        git commit -m "Generated BBE files are added"
        
        sudo snap install hub -- classic
        hub pull-request -m "Update BBE" -b ballerina-dev-website:master -h sumangala028:newBranch
        echo "successfully sent a PR to ballerina-dev-website
      
      


      
